CREATE DATABASE estoque;

USE estoque;

CREATE TABLE estoque (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    quantidade INT NOT NULL
);
SELECT * FROM estoque;

CREATE TABLE Almoxarifado (
	NUMERO_PATRIMONIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ITEM VARCHAR (255) NOT NULL,
    CATEGORIA VARCHAR (255) NOT NULL,
    SETOR VARCHAR (255) NOT NULL,
    RESPONSAVEL VARCHAR (255) NOT NULL
);